package com.zipe.enum

enum class MessageContent {
    AUDIOMESSAGECONTENT,
    FILEMESSAGECONTENT,
    IMAGEMESSAGECONTENT,
    LOCATIONMESSAGECONTENT,
    STICKERMESSAGECONTENT,
    TEXTMESSAGECONTENT,
    UNKNOWNMESSAGECONTENT,
    VIDEOMESSAGECONTENT
}
