server:
  port: 8080

line.bot:
  channel-token: vNdRMDFhuSZWBl0Jj5D0mZk/T7iGtirHCwZ/xme7Q0hH3RDfppTuTsaksLK/WeEqH37gKJxp17aiPT5MIIfHfUSLFt9B1lAmbpTSk3attfdbHSne8OziT0mnhSXkeRu8kixTFUndKq3wSroqHGG6IAdB04t89/1O/w1cDnyilFU=
  channel-secret: 703c0f44af4957ab84b0e59b344dc26e
  handler.path: /callback

hibernate:
  dialect: org.hibernate.dialect.MySQL57Dialect
  show_sql: false
  format_sql: false
  factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  use_second_level_cache: true
  use_query_cache: true
  use_minimal_puts: true
  hbm2ddl_auto: none

spring:
  profiles:
    active: dev
  application:
    name: Line-Bot
  mvc:
    throw-exception-if-no-handler-found: true
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      autoCommit: false
      connectionTestQuery: SELECT 1

  redis:
    host:
    port:
    database:
    password:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
      shutdown-timeout: 100
    timeout: 5000

eureka:
  client:
    enabled: false

application:
  cache:
    enable: true
    key:
      demoCache: PT5M
      userCache: PT5M

log:
  moduleName: LineBot
  base: /home/zipe/tmp/logs
  max:
    history: 100
    size: 100MB

---
spring.config.activate.on-profile: dev
env: dev
spring:
  config:
    import: datasource-dev.properties
  redis:
    host: 192.168.1.150
    port: 6379
    database: 0
    password:

#System config
system:
  job-using-database: true

#Line Info
line:
  push-message-url: https://api.line.me/v2/bot/message/push
  replay-message-url: https://api.line.me/v2/bot/message/reply
  payment-request-url: https://sandbox-api-pay.line.me/v3/payments/request
  payment-confirm-url: https://sandbox-api-pay.line.me/v3/payments/%s/confirm
  payment-confirm-uri: /v3/payments/request
  payment-callback-url: https://line.zipe.idv.tw/line/payment/confirm
  payment-cancel-url: https://line.zipe.idv.tw/line/payment/cancel
  response-success-code: 0000

log:
  root:
    level: DEBUG
---
spring.config.activate.on-profile: sit
env: sit
spring:
  config:
    import: datasource-sit.properties
  redis:
    host: 192.168.1.150
    port: 6379
    database: 0
    password:

#System config
system:
  job-using-database: true

#Line Info
line:
  push-message-url: https://api.line.me/v2/bot/message/push
  replay-message-url: https://api.line.me/v2/bot/message/reply
  payment-request-url: https://sandbox-api-pay.line.me/v3/payments/request
  payment-confirm-url: https://sandbox-api-pay.line.me/v3/payments/%s/confirm
  payment-confirm-uri: /v3/payments/request
  payment-callback-url: https://line.zipe.idv.tw/line/payment/confirm
  payment-cancel-url: https://line.zipe.idv.tw/line/payment/cancel
  response-success-code: 0000

log:
  root:
    level: INFO
---
